### ISSUE TITLE
BUG:std::vector is not introduced, etc

### ISSUE THREAD

**Issue by rockm3** [CIFASIS/sb-graph#31]
1. like:
![2395087168](https://github.com/user-attachments/assets/63c92bde-f316-4244-84e5-fda601980cd1)

dir: 3rd-party/sbg/sb-graph-dev/util/defs.hpp

**Comment by Kalashnikovni** [comment]
Is there any error while building the project?

**Comment by rockm3** [comment]
yes,The vector header file is missing.

**Comment by rockm3** [comment]
![1937842964](https://github.com/user-attachments/assets/eac74817-94b8-4f39-918a-c7dd90743ede)
like this!

**Comment by rockm3** [comment]
maybe autoconf 2.71？I'll try again

**Comment by rockm3** [comment]
This is independent of the autoconf version
